swagger: '2.0'
info:
  description: This is an Api server for 18th Appjam entry ''.  You can find out more at [https://github.com/appjam18/appjam18-backend](https://github.com/appjam18/appjam18-backend).
  version: 1.0.0
  title: Appjam18
  # put the contact info for your development or API team
  contact:
    email: wisemuji@gmail.com

  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /signup:
    post:
      tags:
      - Auth
      summary: Signing up user
      operationId: signup
      description: ""
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: body
        name: Users object
        description: Put new Users object
        schema:
          $ref: '#/definitions/Users'
      responses:
        200:
          description: user signed up
        400:
          description: invalid input, object invalid
        409:
          description: user already exists
  /signin:
    post:
      tags:
      - Auth
      summary: Signing in user
      operationId: signin
      description: ""
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: "email"
        in: "query"
        description: "The user email for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        200:
          description: user logined
        400:
          description: invalid input, object invalid
  /setGroup:
    post:
      tags:
      - Group
      summary: Add new Group
      operationId: setGroup
      description: ""
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: body
        name: Groups object
        description: Put new Group object(key "token" is autogenerated)
        schema:
          $ref: '#/definitions/Groups'
      responses:
        200:
          description: new group added
        400:
          description: invalid input, object invalid
        409:
          description: group already exists
definitions:
  Users:
    type: object
    required:
    - name
    - email
    - phone
    - password
    properties:
      name:
        type: string
        example: Suhyeon Kim
      email:
        type: string
        format: email
        example: te@st.com
      phone:
        type: string
        example: '010-0000-0000'
      password:
        type: string
        example: '0000'
      group:
        type: array
        items: 
          $ref: '#/definitions/tokens'
        description: token of user's groups
  Groups:
    required:
    - token
    - name
    properties:
      token:
        type: string
        example: rsdcx98wefsdcxz
      name:
        type: string
        example: Happy Group
      members:
        type: array
        items: 
          $ref: '#/definitions/tokens'
        description: token of group's members
      boards:
        type: array
        items: 
          $ref: '#/definitions/tokens'
        description: token of group's boards
  Boards:
    required:
    - token
    - name
    properties:
      isNotice:
        type: string
        example: true
        description: check the board if it's notice
      title:
        type: string
        example: Nice Board
      content:
        type: string
        example: Haha Seong yeon is very cute.
      images:
        type: array
        items: 
          $ref: '#/definitions/images'
        description: uploaded images
  tokens:
    type: object
    required:
    - token
    properties:
      token:
        type: string
        example: iu2k343kj223lk
  images:
    type: object
    required:
    - id
    - url
    properties:
      id:
        type: string
        example: wefd3scgwsd23
      url:
        type: string
        example: /img/img.jpg
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /wisemuji/Scanus/1.0.0
# schemes:
#  - http
# Added by API Auto Mocking Plugin
# schemes:
#  - http
# Added by API Auto Mocking Plugin
schemes:
 - https
 - http